# Generated by Django 5.0.1 on 2024-02-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_department',
            field=models.BooleanField(default=False, verbose_name='Is department'),
        ),
    ]
