# Generated by Django 5.0.1 on 2024-02-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0004_remove_user_is_employee_user_is_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timer', models.PositiveIntegerField()),
                ('date', models.DateField(null=True, blank=True)),
            ],
        ),
    ]
