# Generated by Django 5.0.1 on 2024-02-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0007_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
