# Generated by Django 5.0.1 on 2024-02-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0008_delete_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
