# Generated by Django 5.0.1 on 2024-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0009_user_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
