# Generated by Django 5.0.2 on 2024-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0012_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
