# Generated by Django 5.0.2 on 2024-03-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0013_question_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
    ]
