# Generated by Django 5.0.2 on 2024-03-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0015_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
