# Generated by Django 5.0.2 on 2024-03-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0019_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='files/resources/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='files/thumbnails/'),
        ),
    ]
