# Generated by Django 5.0.2 on 2024-03-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0021_alter_course_is_active_alter_course_title_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
