# Generated by Django 5.0.2 on 2024-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0023_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
