# Generated by Django 5.0.2 on 2024-04-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0026_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
