# Generated by Django 5.0.2 on 2024-04-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0027_exam_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=15),
        ),
    ]
