# Generated by Django 5.0.2 on 2024-04-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0029_user_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
