# Generated by Django 5.0.2 on 2024-04-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0032_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
