# Generated by Django 5.0.2 on 2024-04-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0033_resource_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='name',
        ),
    ]
