# Generated by Django 5.0.2 on 2024-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0036_user_is_instructor_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
