# Generated by Django 5.0.2 on 2024-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0040_remove_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
