# Generated by Django 5.0.2 on 2024-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0043_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credential_status',
            field=models.BooleanField(default=False, verbose_name='Credential Status'),
        ),
    ]
