# Generated by Django 5.0.2 on 2024-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0044_user_credential_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
