# Generated by Django 5.0.2 on 2024-05-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0046_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
