# Generated by Django 5.0.2 on 2024-05-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seepsApp', '0047_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
